#!/bin/bash


IMAGE="n2n"

extra_volume_argument=""
for volume in ${VOLUMES}
do
    extra_volume_argument="${extra_volume_argument} -v ${volume}"
done

# Need to make sure wildcards are not expanded here.
cmd=""
for x in "$@"
do
    if echo "$x" | grep '*' > /dev/null; then
        cmd="$cmd \"$x\""
    else
        cmd="$cmd $x"
    fi
done

docker run -it --rm \
    --runtime=nvidia \
    -v $(pwd):/home/n2n \
    -v /tmp:/tmp \
    ${extra_volume_argument} \
    ${IMAGE} \
    bash -c "${cmd}"