#!/bin/bash


REMOTE_DIR="~/dev/noise2noise"

if [[ -z "$1" ]]; then
    echo "Usage: $0 [up|down]"
    exit 1
else
    direction=$1
fi

if [[ -z "$REMOTE" ]]; then
    echo "Need to set REMOTE"
    exit 1
fi

sync_up_inclusions="
    --include *.py
    --include /scripts/*
    --include Dockerfile"

sync_down_inclusions="
    --include *.ipynb"

if [[ "${direction}" == "up" ]]; then
    ssh ${REMOTE} mkdir -p "${REMOTE_DIR}"
    rsync -r --include "*/" ${sync_up_inclusions} --exclude "*" . "${REMOTE}:${REMOTE_DIR}/"
elif [[ "${direction}" == "down" ]]; then
    rsync -r --include "*/" ${sync_down_inclusions} --exclude "*" "${REMOTE}:${REMOTE_DIR}/" .
else
    echo "Invalid direction."
    exit 1
fi