#!/bin/bash


SESSION_NAME="n2n"

tmux has-session -t ${SESSION_NAME} 2>/dev/null
if [ $? -eq 0 ]; then
    tmux attach -t ${SESSION_NAME}
else
    tmux_cmd () {
      keys="$(echo $1 | sed 's/ / Space /g')"
      tmux send-keys ${keys} Enter
    }

    tmux new-session -d -s ${SESSION_NAME}

    tmux split-window -h
    tmux_cmd "htop"

    tmux split-window -v
    tmux_cmd "watch nvidia-smi"

    tmux split-window -v

    tmux select-pane -t 0
    tmux attach-session -d
fi
